table transacoes
	lineageTag: cc361a54-898a-437d-a812-69baee35e737

	measure 'Valor Total' = Sum(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 4a04fefd-e0fe-498e-bc5a-df245b5217b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		lineageTag: 563cdcbf-049d-4fb4-9b70-afb29693c2c0
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bb7e6f74-73e4-42a8-8b8d-e20ba4f346d7
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Total
		dataType: double
		lineageTag: 326b5058-141c-4529-8519-abeaf26bc82b
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		lineageTag: 5716261a-9ddd-41b1-93f2-40a435a5932d
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

